### ISSUE TITLE
숫자야구 게임 만들기

### ISSUE THREAD

**Issue by PHS00** [Team-KakaoJnuBe7/BullsAndCows#1]
## Description

숫자야구 게임을 만들고자 합니다

## Tasks

- [ ] 숫자 랜덤설정
- [ ] 입력 받은 문자열 배열화
- [ ] 배열에서 숫자처리 -> ball and strike
- [ ] 정답체크함수
- [ ] 전체 시스템 처리

## References

- [숫자야구](https://github.com/woowacourse/java-baseball-precourse)
