### ISSUE TITLE
checkNumber 함수 작성

### ISSUE THREAD

**Issue by rnjsgo** [Team-KakaoJnuBe7/BullsAndCows#3]
## Description
Bulls and Cows 게임에서 입력받은 숫자의 Bulls, cows를 판별하는 checkNumber 함수를 작성하고자 합니다.

## Tasks

- [] int[] checkNumber(String origin, String input)
- [] 입력받은 숫자의 각 요소를 Bulls/Cows/none을 판별하여 countBulls(int), countCows(int)를 구해 배열로 반환
- [] 반환하는 배열의 0번째 요소는 Bulls의 개수 , 1번째 요소는 Cows의 개수
## References

- [sample] (address)
